In [15]:
import pyedflib
import numpy as np
import pandas as pd

In [5]:
import numpy as np
data = np.load('data/S001_S001R03.edf.npy')
print(data)

[['0.0' 'T0' '-10.0' ... '24.0' '89.0' '68.0']
 ['0.00625' 'T0' '10.0' ... '25.0' '83.0' '65.0']
 ['0.0125' 'T0' '17.0' ... '34.0' '92.0' '78.0']
 ...
 ['119.98125' 'T0' '-16.0' ... '1.0' '40.0' '17.0']
 ['119.9875' 'T0' '-1.0' ... '8.0' '32.0' '42.0']
 ['119.99375' 'T0' '27.0' ... '16.0' '27.0' '43.0']]

In [12]:
allData = None

for i in range(3, 14):
    # make i a string and 2 digits
    i = str(i).zfill(2)
    data = np.load(f'data/S001_S001R{i}.edf.npy')
    if allData is None:
        allData = data
    else:
        allData = np.vstack((allData, data))

In [14]:
allData.shape

(211200, 66)

In [16]:
pd.DataFrame(allData)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,0.0,T0,-10.0,20.0,7.0,-18.0,0.0,4.0,60.0,4.0,...,-6.0,30.0,25.0,22.0,13.0,-9.0,20.0,24.0,89.0,68.0
1,0.00625,T0,10.0,50.0,49.0,22.0,38.0,31.0,84.0,25.0,...,1.0,44.0,31.0,27.0,25.0,12.0,30.0,25.0,83.0,65.0
2,0.0125,T0,17.0,55.0,59.0,30.0,37.0,25.0,79.0,30.0,...,6.0,48.0,36.0,33.0,34.0,34.0,41.0,34.0,92.0,78.0
3,0.01875,T0,21.0,63.0,66.0,35.0,40.0,29.0,76.0,35.0,...,29.0,48.0,41.0,50.0,59.0,63.0,45.0,47.0,121.0,86.0
4,0.025,T0,27.0,72.0,79.0,48.0,52.0,42.0,91.0,43.0,...,35.0,29.0,22.0,42.0,62.0,71.0,37.0,51.0,143.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211195,119.96875,T0,-2.0,17.0,20.0,42.0,27.0,31.0,31.0,28.0,...,2.0,13.0,11.0,19.0,16.0,5.0,-22.0,-20.0,8.0,-24.0
211196,119.975,T0,5.0,6.0,0.0,11.0,11.0,18.0,18.0,37.0,...,-2.0,3.0,-3.0,7.0,15.0,14.0,-1.0,11.0,53.0,15.0
211197,119.98125,T0,-16.0,-14.0,-18.0,-16.0,-15.0,-7.0,-6.0,-1.0,...,-18.0,-23.0,-27.0,-16.0,-7.0,-9.0,-11.0,1.0,40.0,17.0
211198,119.9875,T0,-1.0,16.0,15.0,27.0,12.0,11.0,11.0,18.0,...,8.0,11.0,1.0,15.0,19.0,27.0,-5.0,8.0,32.0,42.0
211199,119.99375,T0,27.0,46.0,46.0,56.0,39.0,33.0,25.0,48.0,...,-3.0,-8.0,-13.0,3.0,4.0,2.0,1.0,16.0,27.0,43.0